FROM alpine:edge

RUN apk upgrade --update-cache --available
RUN apk add make clang g++

ARG debug

ADD . /eau2
WORKDIR /eau2
RUN make -B build/load_file.exe DEBUG=${debug:-false}
ENTRYPOINT ["./build/load_file.exe"]
CMD ["--ip", "127.0.0.1", "--key", "commits", "--file", "commits.ltgt"]
